FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Brizbee.Dashboard.Server/Brizbee.Dashboard.Server.csproj", "Brizbee.Dashboard.Server/"]
RUN dotnet restore "Brizbee.Dashboard.Server/Brizbee.Dashboard.Server.csproj"
COPY . .
WORKDIR "/src/Brizbee.Dashboard.Server"
RUN dotnet build "Brizbee.Dashboard.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Brizbee.Dashboard.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Brizbee.Dashboard.Server.dll"]
